### ISSUE TITLE
This tool is very well.But I how to use it.

### ISSUE THREAD

**Issue by cnbillow** [siloor/youtube.external.subtitle#1]
Try to change the URL of example,The video can not be displayed.
Can you help me make an example use this URL,
https://www.youtube.com/watch?v=TG0I6Db1lYA
Just one or two word is OK. Thank you.
cnbillow2046@hotmail.com

**Comment by siloor** [comment]
Hey Cnbillow!

I just made you a test site with your given video. You can reach it here:
http://siloor.com/youtube.external.subtitle/static/test1.html

This is just an example, so the subtitle is still from the Kung Fu Panda movie.

The only thing I modified in this embed code compared to the basic example is the video id (from 'fGPPfZIvtCw' to 'TG0I6Db1lYA').

**Comment by cnbillow** [comment]
Thank you very much.and thank you  for development  the so cool tool.

**Comment by siloor** [comment]
I hope it will be useful! Feel free to open an issue, if you find any errors or need a new feature. Also don't forget to star the repository :P
