### ISSUE TITLE
Making the subtitles increase in size proportionately when in fullscreen

### ISSUE THREAD

**Issue by Esn024** [siloor/youtube.external.subtitle#10]
Hello! I was wondering if it's possible to make the subtitles automatically increase in size proportionately when the "fullscreen" button is pressed (I'd like to make it work with the code I posted in the previous issue, where the fullscreen button is paired with multiple videos/subtitles). 

Right now, it's possible to make the font increase in size manually by having the user press Ctrl and + (or Ctrl and - to decrease the font), but that's kind of clunky. It's great to have that as an option, but having the font resizing happen automatically (to whatever the user's screen-size is) would be much better.

Also, a few (perhaps useful) notes:

I've been trying to figure out how to make the subtitles look a bit better... the first thing I did was to replace the black span background behind each subtitle line (which looks ok, but hides a bit too much of the video image for my taste) with a thick black outline around the letters (also spacing them a little wider), using https://owumaro.github.io/text-stroke-generator/ . I replaced line 195 (var firstInit) in youtube.external.subtitle.js with this:

```
	//Creating text outline CSS:
	//https://owumaro.github.io/text-stroke-generator/
	//Roboto, 17px, stroke size 3
	var firstInit = function() {
		var style       = root.document.createElement('style');
		style.id        = 'youtube-external-subtitle-style';
		style.type      = 'text/css';
		style.innerHTML = ".youtube-external-subtitle { position: absolute; display: none; z-index: 0; pointer-events: none; color: #fff; font-family: Roboto, arial, sans-serif; font-size: 17px; text-align: center; letter-spacing: 1.3px;\
		text-shadow: rgb(6, 16, 20) 3px 0px 0px, rgb(6, 16, 20) 2.83487px 0.981584px 0px, rgb(6, 16, 20) 2.35766px 1.85511px 0px, rgb(6, 16, 20) 1.62091px 2.52441px 0px, rgb(6, 16, 20) 0.705713px 2.91581px 0px, rgb(6, 16, 20) -0.287171px 2.98622px 0px, rgb(6, 16, 20) -1.24844px 2.72789px 0px, rgb(6, 16, 20) -2.07227px 2.16926px 0px, rgb(6, 16, 20) -2.66798px 1.37182px 0px, rgb(6, 16, 20) -2.96998px 0.42336px 0px, rgb(6, 16, 20) -2.94502px -0.571704px 0px, rgb(6, 16, 20) -2.59586px -1.50383px 0px, rgb(6, 16, 20) -1.96093px -2.27041px 0px, rgb(6, 16, 20) -1.11013px -2.78704px 0px, rgb(6, 16, 20) -0.137119px -2.99686px 0px, rgb(6, 16, 20) 0.850987px -2.87677px 0px, rgb(6, 16, 20) 1.74541px -2.43999px 0px, rgb(6, 16, 20) 2.44769px -1.73459px 0px, rgb(6, 16, 20) 2.88051px -0.838247px 0px;} \
		.youtube-external-subtitle span { padding: 1px 4px; display: inline-block; margin-bottom: 2px; } .youtube-external-subtitle.fullscreen-ignore { display: none !important; } .youtube-external-subtitle.fullscreen { z-index: 3000000000; }";
```

The next thing I wanted to do is move the physical location of the subtitles a bit lower on the video. Near the end of the file, in the Subtitle.prototype.render function, I changed 

`this.element.style.top = (frame.y + frame.height - 60 - this.element.offsetHeight) + 'px';`

to 

`this.element.style.top = (frame.y + frame.height - 30 - this.element.offsetHeight) + 'px';`

which I think gives a more natural position for the subtitles (even though it overlaps a bit with the Youtube play buttons, but those aren't visible most of the time, so I think it's no problem).

**Comment by siloor** [comment]
Good point, the rendering part is a bit hardcoded for now (the positioning and the fontSize calculation), maybe I will plan a new feature to override the rendering method, so you don't need to modify the original script file.

Two things for the styling of the subtitles:
- when the subtitle is displayed in fullscreen mode, the subtitle element gets a "fullscreen" class, so you can define custom rules for that state. Check the example (green subtitle in fullscreen): [http://siloor.github.io/youtube.external.subtitle/examples/style/](http://siloor.github.io/youtube.external.subtitle/examples/style/)
- the fontSize is set in "em" which is relative to the parent's font size. So for example in the fullscreen example, if you increase the font-size on the "fullscreen-container" with css, the subtitle's fontSize will be also increased.

**Comment by siloor** [comment]
@Esn024 I just added the support for a custom rendering method. I think this will give you full control over displaying the subtitles and you won't need to modify the original script.

Here is the example, I think it is very easy to use it:
http://siloor.github.io/youtube.external.subtitle/examples/customrendermethod/

Let me know if you still need some other feature!

**Comment by Esn024** [comment]
I tried to make the background red in normal mode, and green in fullscreen in the example I posted [here](https://github.com/siloor/youtube.external.subtitle/issues/9#issuecomment-683379088), just like in your [style subtitles example](http://siloor.github.io/youtube.external.subtitle/examples/style/). But for some reason, I can only get the background red in "normal" mode, but it STAYS red even when the video is fullscreen. Also, in your "style subtitles" example the subtitle text seems to get bigger when the video is fullscreen (though I don't see where is the CSS for it...) but that doesn't happen in my example. It's rather frustrating and I'm not sure how to even test for what might be going wrong - any tips would be greatly appreciated.

(I'm trying to set global settings, so I don't actually need video-specific settings)

Here's the code where the fullscreen styling doesn't work:


```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>YouTube External Subtitle</title>
    <base href="../../" />
    <link rel="shortcut icon" href="static/img/favicon/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="static/img/favicon/favicon_32.png" sizes="32x32" />
    <link rel="icon" href="static/img/favicon/favicon_48.png" sizes="48x48" />
    <link rel="icon" href="static/img/favicon/favicon_96.png" sizes="96x96" />
    <link rel="icon" href="static/img/favicon/favicon_144.png" sizes="144x144" />
    <link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="static/css/markdown.css" rel="stylesheet" />
    <link href="static/css/index.css" rel="stylesheet" />
    <!--[if lt IE 9]>
    <script src="static/bootstrap/js/html5shiv.min.js"></script>
    <script src="static/bootstrap/js/respond.min.js"></script>
    <![endif]-->
    <script src="static/js/jquery-1.11.2.min.js"></script>
    <script src="static/bootstrap/js/bootstrap.min.js"></script>
	<style>
  .youtube-external-subtitle span { background: red; }
  .youtube-external-subtitle.fullscreen span { background: green; }
</style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="./">YouTube External Subtitle</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
    </div>
</nav>
<div class="container">
    <style>
        select { padding: 10px; }
    </style>
    <h1>More subtitles, more videos, fullscreen, timing offset, frame rate conversion multiplier, user-editable subtitles</h1>
   <p>You can provide more subtitles to let the users select the one they need.
   <br/>You can have more than one video on a page (enter a unique ID for each video, and enter it into loadMultipleSub() as the second parameter).
    <br/>You can click a button to make a video fullscreen. Hold ctrl and + or ctrl and - to adjust the size of the subtitle text.
	<br/>The multiplier is for converting a subtitle to a different frame rate, if needed. E.g. use '25/24' to convert from 25fps to 24fps (default value is '1').
	<br/>The timing offset can be a positive or negative number of seconds (e.g. '-5.2') to make subtitles properly synced with the video, if needed (default value is '0'). It is applied <i>after</i> the multiplier.
	<br/>Each subtitle can be loaded either from an SRT file location, or from an SRT file encoded as a text string directly on the page.
	<br/>For example, the English subtitles for "Kung Fu Panda 3" below are taken from the textarea at the bottom of the page. The text can be edited by the user, and the result will show up on the video after the button is clicked.

<div id="Youtube_video_fGPPfZIvtCw">
</div>

<div id="Youtube_video_6ZfuNTqbHE8">
</div>

<br/>Partial English subs for Kung Fu Panda 3 trailer. You can edit them, then press the button below to see your changes in the video:<br/>
<textarea id="KFP3ENsubs_partial" rows="4" cols="50">
1
00:00:10,280 --> 00:00:11,500
PO: Master Shifu?

2
00:00:13,400 --> 00:00:14,860
Good time? Bad time?

3
00:00:15,520 --> 00:00:17,800
SHIFU: Time is an illusion,

4
00:00:18,000 --> 00:00:20,960
there is only the now.

5
00:00:20,960 --> 00:00:23,400
PO: So now's a... good time?

6
00:00:23,400 --> 00:00:24,160
SHIFU: Oh...
</textarea>
<br/>
<button onclick="fGPPfZIvtCw()">Reload Kung Fu Panda 3 subs</button> 




<script src="static/youtube.external.subtitle/youtube.external.subtitle.js"></script>
<script src="static/js/subtitles.parser.js"></script>
<script>


//added offset (can be a positive or negative number)
//added multiplier (to convert to different frame rate. E.g. use "25/24" to convert from 25fps to 24fps)
//changed name of "language" to "subChoice" (there might be more than one subtitle per language)

//https://stackoverflow.com/a/47402968
function fractionStrToDecimal(str) {
  return str.split('/').reduce((p, c) => p / c);
}

  var loadSub = function(sub, srtOrString, displayName, multiplier, offset, callback) {
	if (srtOrString === 'srt') {
    var httpRequest = new XMLHttpRequest();

    httpRequest.onreadystatechange = function() {
      if (httpRequest.readyState === XMLHttpRequest.DONE) {
        var subtitles = parser.fromSrt(httpRequest.responseText, true);

        for (var i in subtitles) {
          subtitles[i] = {
            start : subtitles[i].startTime / 1000 * multiplier + offset,
            end   : subtitles[i].endTime / 1000 * multiplier + offset,
            text  : subtitles[i].text
          };
        }

        callback(subtitles);
      }
    };

    httpRequest.open('GET', sub, true);
    httpRequest.send(null);
	} else {
		var subtitles = parser.fromSrt(sub, true);

        for (var i in subtitles) {
          subtitles[i] = {
            start : subtitles[i].startTime / 1000 * multiplier + offset,
            end   : subtitles[i].endTime / 1000 * multiplier + offset,
            text  : subtitles[i].text
          };
        }

        callback(subtitles);
	}
  };

  var loadMultipleSub = function(subs, uniqueID, defaultSub) {
    var result = {};
	
	//first populate the div with the embedded Youtube video, fullscreen button, and "none" subtitle selection
	document.getElementById('Youtube_video_'+uniqueID).innerHTML = '<div id="fullscreen-container_'+uniqueID+'" style="width: 640px; height: 360px;">\
	<iframe id="video_'+uniqueID+'" width="100%" height="100%" src="https://www.youtube.com/embed/'+uniqueID+'" frameborder="0" allowfullscreen="true"></iframe>\
	</div>\
	<button id="fullscreen-btn_'+uniqueID+'">Fullscreen</button>\
	<select id="subChoices_'+uniqueID+'">\
	  <option value="none">-none-</option>\
	</select>';
	
	//now go through each of the subs
	//for multiplier parameter, using fractionStrToDecimal() to convert fraction string to decimal number
	//for offset parameter, *1 to convert string to number
    Object.keys(subs).forEach(function(subChoice) {
      loadSub(subs[subChoice].sub, subs[subChoice].srtOrString, subs[subChoice].displayName, fractionStrToDecimal(subs[subChoice].multiplier), subs[subChoice].offset * 1, function(subtitles) {
        result[subChoice] = subtitles;
		
		//add the subtitle selections to the video, making the default subtitle option "selected"
		console.log(subChoice);
		console.log(defaultSub);
		
		if (subChoice === defaultSub) {
			document.getElementById('subChoices_'+uniqueID).innerHTML += '\n<option value="' + subChoice + '" selected="true">' + subs[subChoice].displayName + '</option>';
		} else {
			document.getElementById('subChoices_'+uniqueID).innerHTML += '\n<option value="' + subChoice + '">' + subs[subChoice].displayName + '</option>';
		}

        if (Object.keys(result).length === Object.keys(subs).length) {
		  
		  var cb = function(result) {
			var youtubeExternalSubtitle = new YoutubeExternalSubtitle.Subtitle(document.getElementById('video_'+uniqueID), result[defaultSub]);

			document.getElementById('subChoices_'+uniqueID).addEventListener('change', function(e) {
			  var subChoice = this.value;

			  youtubeExternalSubtitle.load(result[subChoice]);
			});
			
			//fullscreen
			document.getElementById('fullscreen-btn_'+uniqueID).addEventListener('click', function(e) {
				var elem = document.getElementById('fullscreen-container_'+uniqueID);

				var openFullscreen = function() {
					if (elem.requestFullscreen) {
						elem.requestFullscreen();
					} else if (elem.mozRequestFullScreen) { /* Firefox */
						elem.mozRequestFullScreen();
					} else if (elem.webkitRequestFullscreen) { /* Chrome, Safari & Opera */
						elem.webkitRequestFullscreen();
					} else if (elem.msRequestFullscreen) { /* IE/Edge */
						elem.msRequestFullscreen();
					}
				};

				openFullscreen();
				});
		  };
		  
		  cb(result);
		  
        }
      });
    });
  };

//putting the Kung Fu Panda 3 video loadMultipleSub() into a function; it needs to load once when the page loads, and again whenever the user edits the subtitle text and clicks the button to update the subtitles. The var KP3ENsubs, also, needs to be refreshed each time the button is clicked.
function fGPPfZIvtCw() {
var KP3ENsubs = document.getElementById("KFP3ENsubs_partial").value;
console.log(KP3ENsubs);

  loadMultipleSub({
    en: {sub: KP3ENsubs, srtOrString: 'string', displayName: 'English', multiplier: '1', offset: '0'},
    hu: {sub: 'static/srt/kung_fu_panda_3_trailer_hu.srt', srtOrString: 'srt', displayName: 'Hungarian', multiplier: '1', offset: '1'}
  }, 
  'fGPPfZIvtCw', 
  'en');
  }
//load it the first time when the page loads
fGPPfZIvtCw();
  
//on the other hand, the Avengers video loadMultipleSub() doesn't need to go into a function, because it only needs to load once at the beginning
  loadMultipleSub({
    en: {sub: 'static/srt/avengers_infinity_war_trailer.srt', srtOrString: 'srt', displayName: 'English', multiplier: '1', offset: '0'},
    hu: {sub: 'static/srt/avengers_infinity_war_trailer_hu.srt', srtOrString: 'srt', displayName: 'Hungarian', multiplier: '1', offset: '1'},
    de: {sub: 'static/srt/avengers_infinity_war_trailer_de.srt', srtOrString: 'srt', displayName: 'German', multiplier: '1', offset: '1'}
  }, 
  '6ZfuNTqbHE8', 
  'en');
</script>
	
	
	
	
</div>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-127764423-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-127764423-1');
</script>
</body>
</html>

```

**Comment by Esn024** [comment]
Apologies... I realized that I was accidentally using the OLD version of your youtube.subtitles.js file, which was why it wasn't working. I see you've made a lot of changes to it.

A question: what does this bit do:

`element.style.fontSize = frame.height / 260 + "em";`

Is that why the font size when the video is fullscreen seems to change now, though I don't see where the font-size CSS is defined for fullscreen? Why specifically 260?

I did finally manage to get different styles for regular and fullscreen, though I'm afraid I did it by simply adding style code to the head of the html page, as in your "style" example.

```
	<style>
	
  	//Creating text outline CSS:
	//https://owumaro.github.io/text-stroke-generator/
	//Roboto, 17px, stroke size 3
	

 .youtube-external-subtitle.fullscreen-ignore { display: none !important; } 
  
  /* .youtube-external-subtitle.fullscreen { z-index: 3000000000; }
		*/
		
	.youtube-external-subtitle span { 
	background: none; 
	color: #fff; 
	font-family: Roboto, arial, sans-serif; 
	font-size: 17px; 
	text-align: center; 
	letter-spacing: 1.3px;
	  text-shadow: rgb(6, 16, 20) 3px 0px 0px, rgb(6, 16, 20) 2.83487px 0.981584px 0px, rgb(6, 16, 20) 2.35766px 1.85511px 0px, rgb(6, 16, 20) 1.62091px 2.52441px 0px, rgb(6, 16, 20) 0.705713px 2.91581px 0px, rgb(6, 16, 20) -0.287171px 2.98622px 0px, rgb(6, 16, 20) -1.24844px 2.72789px 0px, rgb(6, 16, 20) -2.07227px 2.16926px 0px, rgb(6, 16, 20) -2.66798px 1.37182px 0px, rgb(6, 16, 20) -2.96998px 0.42336px 0px, rgb(6, 16, 20) -2.94502px -0.571704px 0px, rgb(6, 16, 20) -2.59586px -1.50383px 0px, rgb(6, 16, 20) -1.96093px -2.27041px 0px, rgb(6, 16, 20) -1.11013px -2.78704px 0px, rgb(6, 16, 20) -0.137119px -2.99686px 0px, rgb(6, 16, 20) 0.850987px -2.87677px 0px, rgb(6, 16, 20) 1.74541px -2.43999px 0px, rgb(6, 16, 20) 2.44769px -1.73459px 0px, rgb(6, 16, 20) 2.88051px -0.838247px 0px;
	}
	
  .youtube-external-subtitle.fullscreen span { 
  font-size: 0.7em; 
  letter-spacing: 0.07em;
  text-shadow: rgb(0, 0, 0) 3px 0px 0px, rgb(0, 0, 0) 2.83487px 0.981584px 0px, rgb(0, 0, 0) 2.35766px 1.85511px 0px, rgb(0, 0, 0) 1.62091px 2.52441px 0px, rgb(0, 0, 0) 0.705713px 2.91581px 0px, rgb(0, 0, 0) -0.287171px 2.98622px 0px, rgb(0, 0, 0) -1.24844px 2.72789px 0px, rgb(0, 0, 0) -2.07227px 2.16926px 0px, rgb(0, 0, 0) -2.66798px 1.37182px 0px, rgb(0, 0, 0) -2.96998px 0.42336px 0px, rgb(0, 0, 0) -2.94502px -0.571704px 0px, rgb(0, 0, 0) -2.59586px -1.50383px 0px, rgb(0, 0, 0) -1.96093px -2.27041px 0px, rgb(0, 0, 0) -1.11013px -2.78704px 0px, rgb(0, 0, 0) -0.137119px -2.99686px 0px, rgb(0, 0, 0) 0.850987px -2.87677px 0px, rgb(0, 0, 0) 1.74541px -2.43999px 0px, rgb(0, 0, 0) 2.44769px -1.73459px 0px, rgb(0, 0, 0) 2.88051px -0.838247px 0px;
  }
</style>
```

I noticed that for some reason, the font-size in fullscreen mode would remain the same as the non-fullscreen unless I had the following line in there:
` .youtube-external-subtitle.fullscreen-ignore { display: none !important; } `

However, I seem to have disabled that dynamic resizing code by doing that. I don't have much experience with CSS, so I'm kind of muddling through here, I'm afraid...

Also, the reason I put the style at the head of the page instead of using the custom render method is A) I wasn't sure I could modify everything I wanted to modify (like text-shadow and letter-spacing), B) I felt some trepidation about changing my modification of your code and possibly breaking something, as I've been working on something else for the past week and have forgotten things a bit. Is there any disadvantage to just doing it this way?

**Comment by Esn024** [comment]
Okay, after a good night's sleep I figured out what I was doing wrong. I just needed to put my style inside style.innerHTML on line 150 of youtube.external.subtitle.js:

`        style.innerHTML = "\n    ." + CSS.CLASS + " { position: absolute; display: none; z-index: 0; pointer-events: none; color: #fff; font-family: Roboto, arial, sans-serif; font-weight: normal; font-size: 17px; text-align: center; letter-spacing: 1.3px; text-shadow: rgb(6, 16, 20) 3px 0px 0px, rgb(6, 16, 20) 2.83487px 0.981584px 0px, rgb(6, 16, 20) 2.35766px 1.85511px 0px, rgb(6, 16, 20) 1.62091px 2.52441px 0px, rgb(6, 16, 20) 0.705713px 2.91581px 0px, rgb(6, 16, 20) -0.287171px 2.98622px 0px, rgb(6, 16, 20) -1.24844px 2.72789px 0px, rgb(6, 16, 20) -2.07227px 2.16926px 0px, rgb(6, 16, 20) -2.66798px 1.37182px 0px, rgb(6, 16, 20) -2.96998px 0.42336px 0px, rgb(6, 16, 20) -2.94502px -0.571704px 0px, rgb(6, 16, 20) -2.59586px -1.50383px 0px, rgb(6, 16, 20) -1.96093px -2.27041px 0px, rgb(6, 16, 20) -1.11013px -2.78704px 0px, rgb(6, 16, 20) -0.137119px -2.99686px 0px, rgb(6, 16, 20) 0.850987px -2.87677px 0px, rgb(6, 16, 20) 1.74541px -2.43999px 0px, rgb(6, 16, 20) 2.44769px -1.73459px 0px, rgb(6, 16, 20) 2.88051px -0.838247px 0px; }\n    ." + CSS.CLASS + " span { background: none; padding: 1px 4px; display: inline-block; margin-bottom: 2px; }\n    ." + CSS.CLASS + "." + CSS.FULLSCREEN_IGNORE + " { display: none !important; }\n    ." + CSS.CLASS + "." + CSS.FULLSCREEN + " { z-index: 3000000000; }\n  ";`

Now everything seems to scale properly when the height of the display changes. Since I plan to have site-wide style settings for the subtitles, that works for me. 

However, as an unfortunate side-effect, it is no longer possible for the user to over-ride the default subtitle size settings by pressing Ctrl + or Ctrl - (Or Ctrl and mouse scroll wheel) while the video is playing. It works for ONE subtitle (I can get the text size to shrink while ONE subtitle is displayed), but as soon as the next subtitle starts, it's back to the default size.
Do you think it would work to have buttons on the page that adjust the `element.style.fontSize` value from `frame.height / 260 + "em"` to something else, say, increase/decrease the value by 10%?

Also, the issue with portrait mode is still there (see paragraph 3 of my last post).

I guess these are more minor issues now, though. Thanks for all your help in getting scaling based on height to work (although I realize the past few posts have mostly been me bumbling around your code and making some obvious mistakes...).
