### ISSUE TITLE
How difficult would it be to add other sites? Dailymotion, Vimeo, etc.

### ISSUE THREAD

**Issue by Esn024** [siloor/youtube.external.subtitle#12]
Hello,
I recently launched a site which uses a modification of your code - [here](https://www.animatsiya.net) (incidentally, how should I give attribution? Right now I just have a mention at the bottom of [the DIY page](https://www.animatsiya.net/diy.php) - is that okay, or would something else be better?)

My question is, how easily could this code be adapted to work for Youtube competitors such as Dailymotion or Vimeo? Dailymotion seems to be the 2nd-biggest video site overall, and I've noticed that there has been a particular trend for some years now among some directors and studios to upload to Vimeo instead of Youtube. I've always wanted to have an option besides Youtube.

I haven't looked much into the particulars of how Youtube External Subtitle works, so... I'd appreciate hearing your perspective.

**Comment by siloor** [comment]
Hello @Esn024 ,

At first, sorry for the late answer.

For me it is not necessary to mention the original script on your site. But of course if you do, I appreciate it :) I think you site looks really cool!

Well, I think it wouldn't be that hard to support other sites as well.

We only have Youtube specific logic by getting the id of the video from the url, and also by checking the current time position of the playback. These are the only things needed to display the subtitles.

So I would say, that it is relatively easy to implement it, although I'm not planning to support other video sites in this script.

**Comment by Esn024** [comment]
Thanks. :)

"We only have Youtube specific logic by getting the id of the video from the url, and also by checking the current time position of the playback. These are the only things needed to display the subtitles."

Could you please point out the lines in the code where those things are done? I'm trying to understand enough of how it works to make the necessary changes myself. There's a lot here I don't get yet, but every little bit would help.

There seem to be quite a lot of lines in the code that have to do with Youtube player API functions and for which I'd need to write alternative logic, so I'm just trying to identify all of them...

Also, does "getVideoData()" work? It's not mentioned in the Youtube player API reference, and a search online says that it has been removed...

**Comment by Esn024** [comment]
Also, I was wondering, what was the reason that the file structure was changed in Mar 30 of last year, and the one .js file separated out into multiple .ts files?
