### ISSUE TITLE
Update subtitles on video time change

### ISSUE THREAD

**Issue by arcadeus** [siloor/youtube.external.subtitle#14]
During normal playback, subtitles are updated ok.
But when I rewind or forward video by moving youtube's bottom control or by pressing Arrows Left or Right, nothing happens, subtitles are not updated.

**Comment by siloor** [comment]
Hello @arcadeus !

You are totally right, the subtitle renderer wasn't called immediatelly after youtube's play event, only after 500 milliseconds.

Now it is fixed, thanks for letting me know!
