### ISSUE TITLE
Let use inner YT.Player object outside

### ISSUE THREAD

**Issue by arcadeus** [siloor/youtube.external.subtitle#18]
`YT.Player` object created inside `YoutubeExternalSubtitle.Subtitle` may be useful for many purposes outside it.
Creating 2nd own `YT.Player` doesn't work.
So now we can't use `YoutubeExternalSubtitle.Subtitle` and `YT.Player` in the same web page together.
The suggestion is to add a public method to `YoutubeExternalSubtitle.Subtitle`, which returns inner `_this.player`.

**Comment by siloor** [comment]
Very good idea, thank you!

I just created the `getYTPlayer` method, which returns the `this.player`.
