### ISSUE TITLE
Issues in Firefox fullscreen and iOS

### ISSUE THREAD

**Issue by htamhue** [siloor/youtube.external.subtitle#2]
First thing I want to thank you for creating this awesome plugin.
I found an issue when open fullscreen in Firefox, the subtitle is below the video even when I add the flag "html5=1" in the embed link.
The other issue is on iOS, I add "fs=0" to the embed link, work well on Android, but can't open the video in safari on iOS, and the video still open in fullscreen in Chrome on iOS.
Can you help me?
Thanks in advance

**Comment by siloor** [comment]
Hi htamhue!

Yes, sadly these are all true.

In Firefox, only the element requesting the fullscreen mode can be visible, in this case the embedded video's frame (and we can't inject elements to that frame). I tried a lot of things to hack it, but nothing worked.

By iOS (actually it is just the iphone and the ipod) videos are always playing in fullscreen mode, there is no option to play a video inline. There is a workaround to do it (https://github.com/amirch1/VideoInline), but for that you need to have access to the video element. So by embedded YouTube videos it won't work.

**Comment by ShunSakurai** [comment]
Hello @siloor,
Thank you very much for creating this great tool. I'm using it on my website: https://work-graph.jp/en/
I found that recently there's a way to prevent fullscreen play on iOS Safari, with `playsinline=1` parameter in src URL.
Please see: https://stackoverflow.com/questions/33367473/display-youtube-video-inline-on-ios-devices
Hope this helps!

**Comment by siloor** [comment]
Hello @ShunSakurai ,

I'm very glad that you found this script useful.

Thank you for the tip! I already added the `playsinline=1` parameter to the script.
