### ISSUE TITLE
how to clear / unload subtitles from video

### ISSUE THREAD

**Issue by shaktis110** [siloor/youtube.external.subtitle#24]
hello, sir thanks for this awesome project. I just want to know how to unload (clear) subtitles from a video

**Comment by milan-magyar** [comment]
Hello @shaktis110 !

I'm glad that you find the project useful.

The `YoutubeExternalSubtitle.Subtitle` class has a public destroy method.

You can use it like:
```
var youtubeExternalSubtitle = new YoutubeExternalSubtitle.Subtitle(videoElement, subtitle);

youtubeExternalSubtitle.destroy();
```

**Comment by shaktis110** [comment]
thank you so much sir
