### ISSUE TITLE
Subtitle doesn't show in fullscreen mode

### ISSUE THREAD

**Issue by kwangminnoh** [siloor/youtube.external.subtitle#5]
Hi,

I'm using your javascript to show translated subtitles for youtube videos.
Lately, in fullscreen mode, subtitles doesn't show both on PC and Mobile.
I remember it worked before on PC(but not on mobile).
If you can look that up to fix it, that would be nice.

Thank you for your works.

**Comment by siloor** [comment]
Hello,

Yes, sadly that is the case now. Even Chrome disabled to display anything above an iframe, if the iframe is in fullscreen mode. So as I see there is no way to display subtitle in front of an embedded youtube video.

**Comment by kwangminnoh** [comment]
I see.
Anyway, thank you again for your works.
It really helps me do my work.

https://drumtubekorea.blogspot.com
if you wonder what I am doing, just drop by to see how I use your codes.

Thanks.

**Comment by wire67** [comment]
Would it be possible to have an area bellow the iframe? Somehow forcing the iframe to be maxheight 90% then the subs in the remaining 10%?

**Comment by siloor** [comment]
> Would it be possible to have an area bellow the iframe? Somehow forcing the iframe to be maxheight 90% then the subs in the remaining 10%?

No, sadly the script can't alter the content of the iframe and in fullscreen mode the iframe requires the whole screen.

**Comment by wire67** [comment]
- Seems we can disable the full screen button (double click still available).
<iframe id="video" src="https://www.youtube-nocookie.com/embed/xxx?controls=0" width="100%" height="400" frameborder="0" allowfullscreen="0"></iframe>
- So we could add "our own" full screen button on the small video, in the corner.
- When the user clicks on it, we could change the height="400" to browser height, then a message could tell the desktop user to press F11 to have the true full screen with subs. On mobile, browsers are almost full screen anyway.
